//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsApp.SrvRefProveedor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8733/WcfService/ServiceProveedor", ConfigurationName="SrvRefProveedor.IServiceProveedor")]
    public interface IServiceProveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/WcfService/ServiceProveedor/IServiceProveedor/GetData", ReplyAction="http://localhost:8733/WcfService/ServiceProveedor/IServiceProveedor/GetDataRespon" +
            "se")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/WcfService/ServiceProveedor/IServiceProveedor/GetData", ReplyAction="http://localhost:8733/WcfService/ServiceProveedor/IServiceProveedor/GetDataRespon" +
            "se")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProveedorChannel : FormsApp.SrvRefProveedor.IServiceProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProveedorClient : System.ServiceModel.ClientBase<FormsApp.SrvRefProveedor.IServiceProveedor>, FormsApp.SrvRefProveedor.IServiceProveedor {
        
        public ServiceProveedorClient() {
        }
        
        public ServiceProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
