//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsApp.WCF_Productos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8733/WcfService/Service_Productos", ConfigurationName="WCF_Productos.IProductos")]
    public interface IProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/WcfService/Service_Productos/IProductos/_GetData", ReplyAction="http://localhost:8733/WcfService/Service_Productos/IProductos/_GetDataResponse")]
        string _GetData(string value, string _DataRow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/WcfService/Service_Productos/IProductos/_GetData", ReplyAction="http://localhost:8733/WcfService/Service_Productos/IProductos/_GetDataResponse")]
        System.Threading.Tasks.Task<string> _GetDataAsync(string value, string _DataRow);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosChannel : FormsApp.WCF_Productos.IProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.ClientBase<FormsApp.WCF_Productos.IProductos>, FormsApp.WCF_Productos.IProductos {
        
        public ProductosClient() {
        }
        
        public ProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string _GetData(string value, string _DataRow) {
            return base.Channel._GetData(value, _DataRow);
        }
        
        public System.Threading.Tasks.Task<string> _GetDataAsync(string value, string _DataRow) {
            return base.Channel._GetDataAsync(value, _DataRow);
        }
    }
}
