//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsApp.SrvRef_Usr {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/", ConfigurationName="SrvRef_Usr.IService_Usr")]
    public interface IService_Usr {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/i" +
            "nsUsr", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/i" +
            "nsUsrResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        void insUsr(object[] objUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/i" +
            "nsUsr", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/i" +
            "nsUsrResponse")]
        System.Threading.Tasks.Task insUsrAsync(object[] objUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/u" +
            "pdUsr", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/u" +
            "pdUsrResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        void updUsr(object[] objUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/u" +
            "pdUsr", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/u" +
            "pdUsrResponse")]
        System.Threading.Tasks.Task updUsrAsync(object[] objUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/d" +
            "elUsr", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/d" +
            "elUsrResponse")]
        void delUsr(int idUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/d" +
            "elUsr", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/d" +
            "elUsrResponse")]
        System.Threading.Tasks.Task delUsrAsync(int idUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "et_id_nom_roles", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "et_id_nom_rolesResponse")]
        int get_id_nom_roles(int idUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "et_id_nom_roles", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "et_id_nom_rolesResponse")]
        System.Threading.Tasks.Task<int> get_id_nom_rolesAsync(int idUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "etListUsrs", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "etListUsrsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        object[][] getListUsrs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "etListUsrs", ReplyAction="http://localhost:8733/Design_Time_Addresses/WcfService/Service_Usr/IService_Usr/g" +
            "etListUsrsResponse")]
        System.Threading.Tasks.Task<object[][]> getListUsrsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_UsrChannel : FormsApp.SrvRef_Usr.IService_Usr, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_UsrClient : System.ServiceModel.ClientBase<FormsApp.SrvRef_Usr.IService_Usr>, FormsApp.SrvRef_Usr.IService_Usr {
        
        public Service_UsrClient() {
        }
        
        public Service_UsrClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_UsrClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_UsrClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_UsrClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insUsr(object[] objUsr) {
            base.Channel.insUsr(objUsr);
        }
        
        public System.Threading.Tasks.Task insUsrAsync(object[] objUsr) {
            return base.Channel.insUsrAsync(objUsr);
        }
        
        public void updUsr(object[] objUsr) {
            base.Channel.updUsr(objUsr);
        }
        
        public System.Threading.Tasks.Task updUsrAsync(object[] objUsr) {
            return base.Channel.updUsrAsync(objUsr);
        }
        
        public void delUsr(int idUsr) {
            base.Channel.delUsr(idUsr);
        }
        
        public System.Threading.Tasks.Task delUsrAsync(int idUsr) {
            return base.Channel.delUsrAsync(idUsr);
        }
        
        public int get_id_nom_roles(int idUsr) {
            return base.Channel.get_id_nom_roles(idUsr);
        }
        
        public System.Threading.Tasks.Task<int> get_id_nom_rolesAsync(int idUsr) {
            return base.Channel.get_id_nom_rolesAsync(idUsr);
        }
        
        public object[][] getListUsrs() {
            return base.Channel.getListUsrs();
        }
        
        public System.Threading.Tasks.Task<object[][]> getListUsrsAsync() {
            return base.Channel.getListUsrsAsync();
        }
    }
}
